dellaert_kul_education_xml_base:
    pattern: /
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:index, _locale: nl }

dellaert_kul_education_xml_home:
    pattern:   /{_locale}/
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:index, _locale: nl }
    requirements:
        _locale: nl|en|fr

dellaert_kul_education_xml_list_faculties_by_id_title:
    pattern:   /{_locale}/faculties
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listFacultiesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en|fr

dellaert_kul_education_xml_list_levels_by_id_title_noid:
    pattern:   /{_locale}/levels
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listLevelsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en|fr

dellaert_kul_education_xml_list_levels_by_id_title:
    pattern:   /{_locale}/levels/{fid}
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listLevelsByIdTitle, _locale: nl }
    requirements:
        fid: \d+
        _locale: nl|en|fr

dellaert_kul_education_xml_list_studies_by_id_title_noid:
    pattern:   /{_locale}/studies
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listStudiesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en|fr

dellaert_kul_education_xml_list_studies_by_id_title:
    pattern:   /{_locale}/studies/{fid}/{lid}
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listStudiesByIdTitle, _locale: nl }
    requirements:
        fid: \d+
        lid: \d+
        _locale: nl|en|fr