dellaert_kul_education_xml_base:
    pattern: /
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:index, _locale: nl }

dellaert_kul_education_xml_home:
    pattern:   /{_locale}/
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:index, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_xml_list_faculties_by_id_title:
    pattern:   /{_locale}/faculties
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listFacultiesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_xml_list_levels_by_id_title_noid:
    pattern:   /{_locale}/levels
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listLevelsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_xml_list_levels_by_id_title:
    pattern:   /{_locale}/levels/{fid}
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listLevelsByIdTitle, _locale: nl }
    requirements:
        fid: \d+
        _locale: nl|en

dellaert_kul_education_xml_list_studies_by_id_title_noid:
    pattern:   /{_locale}/studies
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listStudiesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_xml_list_studies_by_id_title:
    pattern:   /{_locale}/studies/{fid}/{lid}
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listStudiesByIdTitle, _locale: nl }
    requirements:
        fid: \d+
        lid: \d+
        _locale: nl|en

dellaert_kul_education_xml_list_programs_by_id_title_noid:
    pattern:   /{_locale}/programs
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listProgramsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_xml_list_programs_by_id_title:
    pattern:   /{_locale}/programs/{sid}
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listProgramsByIdTitle, _locale: nl }
    requirements:
        sid: \d+
        _locale: nl|en

dellaert_kul_education_xml_list_stages_by_id_title_noid:
    pattern:   /{_locale}/stages
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listStagesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_xml_list_stages_by_id_title:
    pattern:   /{_locale}/stages/{pid}
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listStagesByIdTitle, _locale: nl }
    requirements:
        sid: \d+
        _locale: nl|en

dellaert_kul_education_xml_list_courses_by_id_title_noid:
    pattern:   /{_locale}/courses
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listCoursesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_xml_list_courses_by_id_title:
    pattern:   /{_locale}/courses/{pid}/{phid}
    defaults: { _controller: DellaertKULEducationXMLBundle:Main:listCoursesByIdTitle, _locale: nl }
    requirements:
        phid: \d+
        sid: \d+
        _locale: nl|en