dellaert_kul_education_api_list_faculties_by_id_title:
    pattern:   /{_locale}/faculties-id-title
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listFacultiesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_api_list_levels_by_id_title_noid:
    pattern:   /{_locale}/levels-id-title
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listLevelsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_api_list_levels_by_id_title:
    pattern:   /{_locale}/levels-id-title/{fid}
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listLevelsByIdTitle, _locale: nl }
    requirements:
        fid: \d+
        _locale: nl|en

dellaert_kul_education_api_list_studies_by_id_title_noid:
    pattern:   /{_locale}/studies-id-title
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listStudiesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_api_list_studies_by_id_title:
    pattern:   /{_locale}/studies-id-title/{fid}/{lid}
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listStudiesByIdTitle, _locale: nl }
    requirements:
        fid: \d+
        lid: \d+
        _locale: nl|en

dellaert_kul_education_api_list_programs_by_id_title_noid:
    pattern:   /{_locale}/programs-id-title
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listProgramsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_api_list_programs_by_id_title:
    pattern:   /{_locale}/programs-id-title/{sid}
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listProgramsByIdTitle, _locale: nl }
    requirements:
        sid: \d+
        _locale: nl|en

dellaert_kul_education_api_list_stages_by_id_title_noid:
    pattern:   /{_locale}/stages-id-title
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listStagesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_api_list_stages_by_id_title:
    pattern:   /{_locale}/stages-id-title/{pid}
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listStagesByIdTitle, _locale: nl }
    requirements:
        sid: \d+
        _locale: nl|en

dellaert_kul_education_api_list_courses_in_level_noids:
    pattern:   /{_locale}/courses-in-level
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listCoursesInLevel, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_api_list_courses_in_level:
    pattern:   /{_locale}/courses-in-level/{pid}/{phid}
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listCoursesInLevel, _locale: nl }
    requirements:
        phid: \d+
        sid: \d+
        _locale: nl|en

dellaert_kul_education_api_list_courses_by_groups_in_level_noids:
    pattern:   /{_locale}/courses-by-groups-in-level
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listCoursesByGroupsInLevel, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_kul_education_api_list_courses_by_groups_in_level:
    pattern:   /{_locale}/courses-by-groups-in-level/{pid}/{phid}
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listCoursesByGroupsInLevel, _locale: nl }
    requirements:
        phid: \d+
        sid: \d+
        _locale: nl|en

dellaert_kul_education_api_list_course_details:
    pattern:   /{_locale}/courses-details/{cid}
    defaults: { _controller: DellaertKULEducationAPIBundle:API:listCourseDetails, _locale: nl }
    requirements:
        phid: \d+
        sid: \d+
        _locale: nl|en
